name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: make ci
      
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Cpplint
      run: |
        sudo apt-get update
        sudo apt-get install python3-pip
        pip install --user cpplint
    - name: Run Linting
      run: make test-lint
      
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run Test Suite
      run: make test-ci
    